[[plugins]]
repository = 'Shougo/neobundle.vim'

[[plugins]]
repository = 'Shougo/vimproc.vim'
    [plugins.build]
    windows = 'tools\\update-dll-mingw'
    cygwin  = 'make -f make_cygwin.mak'
    mac     = 'make -f make_mac.mak'
    unix    = 'make -f make_unix.mak'

# complete
[[plugins]]
repository = 'Shougo/neocomplete.vim'
depends    = 'Shougo/context_filetype.vim'
insert     = 1

[[plugins]]
repository = 'Shougo/neosnippet.vim'
depends    = ['Shougo/neosnippet-snippets', 'Shougo/context_filetype.vim']
insert     = 1
filetypes  = 'snippet'
unite_sources = ['neosnippet', 'neosnippet/user', 'neosnippet/runtime']

# Unite
[[plugins]]
repository = 'Shougo/unite.vim'
depends    = ['Shougo/neomru.vim', 'Shougo/neoyank.vim']
    [plugins.commands]
    name     = 'Unite'
    complete = 'customlist,unite#complete_source'

[[plugins]]
repository = 'Shougo/unite-outline'

# TOML
[[plugins]]
repository = 'cespare/vim-toml'
filetypes  = 'toml'

[[plugins]]
repository = 'Shougo/vimfiler.vim'
depends    = 'Shougo/unite.vim'
mappings = '<Plug>'
explorer = 1

  [plugins.commands]
  name = ['VimFiler']
  complete = 'customlist,vimfiler#complete'

# MOTION
[[plugins]]
repository = 'rhysd/clever-f.vim'

[[plugins]]
repository = 'jiangmiao/auto-pairs'

[[plugins]]
repository = 'terryma/vim-expand-region'

# COMMENT OUT
[[plugins]]
repository = 'tyru/caw.vim'
mappings   = '<Plug>'

# GIT
[[plugins]]
repository = 'tpope/vim-fugitive'

[[plugins]]
repository = 'airblade/vim-gitgutter'

[[plugins]]
repository = 'rhysd/committia.vim'

[[plugins]]
repository = 'AndrewRadev/gapply.vim'

# QUICKFIX
[[plugins]]
repository = 'dannyob/quickfixstatus'

[[plugins]]
repository = 'cohama/vim-hier'

# SEARCH
[[plugins]]
repository = 'thinca/vim-visualstar'
mappings = [['x', '*'], ['x' , '#'], ['x', 'g*'], ['x', 'g#']]

[[plugins]]
repository = 'haya14busa/incsearch.vim'

# GTAGS
[[plugins]]
repository = '5t111111/alt-gtags.vim'

# SYNTAX CHECK
[[plugins]]
repository = 'scrooloose/syntastic'

# STATUS LINE
[[plugins]]
repository = 'itchyny/lightline.vim'

# COLOR
[[plugins]]
repository = 'w0ng/vim-hybrid'

# QuickRun
[[plugins]]
repository = 'thinca/vim-quickrun'

[[plugins]]
repository = 'tyru/open-browser.vim'
filetypes  = 'markdown'

# file swap
[[plugins]]
repository = 'koara-local/next-alter.vim'
filetypes  =  ['c', 'cpp']

# Langage syntax
# python
[[plugins]]
repository = 'davidhalter/jedi-vim'
filetypes  = 'python'
    [plugins.build]
    others = 'git submodule update --init'

# C/C++
[[plugins]]
repository = 'Rip-Rip/clang_complete'
filetypes  =  ['c', 'cpp']

# Qt
[[plugins]]
repository = 'Townk/vim-qt'
filetypes  =  ['c', 'cpp', 'qml']

# QML
[[plugins]]
repository = 'peterhoeg/vim-qml'
filetypes  = 'qml'

# JSON
[[plugins]]
repository = 'elzr/vim-json'
filetypes  = 'json'

# Markdown
[[plugins]]
repository = 'kannokanno/previm'
filetypes  = 'markdown'

[[plugins]]
repository = 'plasticboy/vim-markdown'
filetypes  = 'markdown'

# wayland
[[plugins]]
repository = 'koara-local/vim-wayland'
filetypes  =  ['c', 'cpp']

# Go
[[plugins]]
repository = 'fatih/vim-go'

# Open CL (*.cl)
[[plugins]]
repository = 'frasercrmck/opencl.vim'
filetypes  = 'opencl'

# Open GL
[[plugins]]
repository = 'koara-local/opengl.vim'
lazy = 1

# GLSL
[[plugins]]
repository = 'beyondmarc/glsl.vim'
